#!/bin/sh
# XXX: find another way to enumerate folders without using word splitting
# right now, no " surrounding variables to split with character \n
# rewrite in python to avoid these shenanigans
set -e
set -u

ARCMAIL="archivemail -q --include-flagged"
MAILROOT="$HOME/.mail"
ARCDIR="$MAILROOT/archives"

## POLY
ARCPOLY="$ARCMAIL --output-dir=$ARCDIR/poly"
POLY=$(cat <<EOF
$MAILROOT/poly/Inbox/
$MAILROOT/poly/Sent/
EOF
)
$ARCPOLY -d 1 $POLY

## CAYL
ARCCAYL="$ARCMAIL --output-dir=$ARCDIR/cayl"
CAYL=$(cat <<EOF
$MAILROOT/cayl/Inbox/
$MAILROOT/cayl/Sent/
EOF
)
$ARCCAYL -d 365 $CAYL

## YAQH
ARCYAQH="$ARCMAIL --output-dir=$ARCDIR/yaqh"
YAQH=$(cat <<EOF
$MAILROOT/yaqh/Inbox/
$MAILROOT/yaqh/Sent/
EOF
)
$ARCYAQH -d 365 $YAQH

## ETHZ
ARCETHZ="$ARCMAIL --output-dir=$ARCDIR/ethz"
ETHZ=$(cat <<EOF
$MAILROOT/ethz/Inbox/
$MAILROOT/ethz/Sent*
$MAILROOT/ethz/moeb/
EOF
)
$ARCETHZ $ETHZ

## SYS
ARCSYS="$ARCMAIL --output-dir=$ARCDIR/sys"
SYS=$(cat <<EOF
/var/mail/*
EOF
)
$ARCSYS -d 21 $SYS
