#!/bin/sh
set -e
set -u
# shellcheck source=/dev/null
. $HOME/.zsh/11_locals.zsh

DATETAG="$(date +%F_%s)"
sudo -i -u hiq cp "$MOBILE_DIR"/keepass/keepass_bdd.kdbx ~/backups/keepass/keepass_bdd_"$DATETAG".kdbx
sudo -i -u hiq cp -r "$TODO_DIR" ~/backups/TODO/TODO_"$DATETAG"
sudo -i -u hiq cp -r ~/.calcurse ~/backups/calcurse/calcurse_"$DATETAG"
