#!/bin/sh
set -e
set -u

LOG="$HOME"/.tmp/checkmail
date >> "$LOG"

# For notmuch and imapfilter
. "$HOME"/.zsh/10_globals.zsh
. "$HOME"/.zsh/11_locals.zsh

imapfilter >> "$LOG"
mbsync -q -c "${XDG_CONFIG_HOME:-$HOME/.config}"/mbsync/mbsyncrc -a >> "$LOG"

# For notmuch
. "$HOME"/.zsh/10_globals.zsh
. "$HOME"/.zsh/11_locals.zsh

# cat to avoid non-zero return value from grep
notmuch new -q 2>&1 >/dev/null |\
  grep -v "Note: Ignoring non-mail file:" |\
  cat >> "$LOG"
