#!/bin/bash
# Compare the list of dot files in $HOME with an allow list, and update the
# list or delete the files.
set -e
set -u

ALLOW_LIST="${XDG_CONFIG_HOME:-$HOME}"/dotfiles.allowed
touch "$ALLOW_LIST"

tmp="$(mktemp)"
find "$HOME" -maxdepth 1 -name '\.*' | sort > "$tmp"
need_update=""
diff "$tmp" "$ALLOW_LIST" || need_update=y

if [ -n "$need_update" ]; then
  select choice in "Update the allow list" "Remove forbidden dotfiles" "Do nothing"; do
    case $choice in
      "Update the allow list")
        echo Updating the list.
        mv "$tmp" "$ALLOW_LIST"
        break
        ;;
      "Remove forbidden dotfiles")
        echo Trashing forbidden dotfiles:
        while read -r file ; do
          if ! grep -q "$file" "$ALLOW_LIST"; then
            printf "%s\n" "$file"
            trash "$file"
          fi
        done < "$tmp"
        break
        ;;
      *)
        echo "$choice"
        echo Doing nothing.
        break
        ;;
    esac
  done
else
  echo "Home folder compliant, nothing to do."
fi
