#!/bin/sh
set -e
set -u


imapfilter
mbsync -c "${XDG_CONFIG_HOME:-$HOME/.config}"/mbsync/mbsyncrc -a

# for notmuch
. "$HOME"/.zsh/11_locals.zsh
notmuch new 2>&1 | grep -v "Note: Ignoring non-mail file:"
