#!/bin/bash
# Compare the list of dot files in $HOME with an allow list and a forbidden
# list, and update the lists or delete the files. Make it faster to answer "do I
# have all my dotfiles checked in?".
set -e
set -u

REMOVE_LIST="${XDG_CONFIG_HOME:-$HOME}"/dotfiles.remove
ALLOW_LIST="${XDG_CONFIG_HOME:-$HOME}"/dotfiles.allowed

touch "$ALLOW_LIST"
touch "$REMOVE_LIST"

# Removing known forbidden files that keep reappearing.
trash_forbidden(){
  while read -r file; do
    (trash "$file" 2>/dev/null && printf "Trashed %s\n" "$file...") || true
  done < "$REMOVE_LIST"
}

trash_forbidden


file="/home/hiq/.FBReader"
find "$HOME" -maxdepth 1 -name '\.*' | sort | while read -r file ; do

if  grep -q "$file" "$ALLOW_LIST"; then
  continue
fi

if  grep -q "$file" "$REMOVE_LIST"; then
  continue
fi

printf "File: %s not in any list\n" "$file"
tree "$file" | head -n 10

# Subshell required to make the select compatible with the while loop.
(
select choice in "Add to allow list" "Add to remove list" "Do nothing"; do
  case $choice in
    "Add to allow list")
      echo "Add to allow list."
      printf "%s\n" "$file" >> "$ALLOW_LIST"
      break
      ;;
    "Add to remove list")
      echo "Add to remove list."
      printf "%s\n" "$file" >> "$REMOVE_LIST"
      break
      ;;
    *)
      echo "$choice"
      echo Doing nothing.
      break
      ;;
  esac
done
) < /dev/tty
done

# To remove files added to remove list in the meantime.
trash_forbidden
