#!/bin/sh
set -e
set -u
ZDOTDIR="$HOME/.config/zsh"

# For notmuch and imapfilter
. "$ZDOTDIR"/10_globals.zsh
. "$ZDOTDIR"/11_locals.zsh

LOG="$USERTMP"/checkmail
date >> "$LOG"


email_sync(){
  imapfilter >> "$LOG" || return "$?"
  mbsync -q -c "${XDG_CONFIG_HOME:-$HOME/.config}"/mbsync/mbsyncrc -a >> "$LOG" || return "$?"

# cat to avoid non-zero return value from grep
notmuch new -q 2>&1 >/dev/null |\
  grep -v "Note: Ignoring non-mail file:" |\
  cat >> "$LOG"
}

(cd "$HOME"/.mail/ && ./arch.sh) > /dev/null

# retry in case of failures, and ignore errors
email_sync || email_sync
