#!/bin/sh
set -e
set -u
if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
  echo "Usage: $0 INPUT [OUTPUT]"
  return 1
fi
input="$1"

echo "$input"

if [ "$#" -eq 1 ]; then
  output="${input%\.*}_compressed.mkv"
else
  output="$1"
fi

echo "$output"

# use default crf of 28, used to use 28
nice -n 20 ffmpeg -i "$input" -c:v libx265 -crf 28 -c:a libopus -b:a 16k "$output"
