#!/usr/bin/env julia
#= 2018-02-05 First script in Julia! =#
using PyCall
@pyimport mpd

function get_client(addr, port, password=nothing)
  client = mpd.MPDClient(use_unicode=true)
  client[:connect](addr, port)

  if password != nothing
    client[:password](password)
  end

  return client
end

function playing_file_rel(client)
  rel_path = client[:currentsong]()["file"]
  return rel_path
end

function music_root(conf="/.config/mpd/mpd.conf")
  fn =  homedir() * conf
  for ln in eachline(fn)
    if ismatch(r"music_directory", ln)
      return expanduser(split(ln,'"')[2])
    end
  end
  throw(KeyError())
end


function main(tgt = "music/from_mpd")
  mobile_dir = ENV["MOBILE_DIR"]
  port = ENV["MPD_PORT"]
  host = split(ENV["MPD_HOST"],'@')
  password = length(host) == 2 ? host[1] : nothing
  addr = host[end]

  abs_path_tgt = joinpath(mobile_dir, tgt)
  mkpath(abs_path_tgt)

  root = music_root()

  client = get_client(addr, port, password)
  from = joinpath(root, playing_file_rel(client))

  tgt = joinpath(abs_path_tgt, basename(from))

  try
    cp(from, tgt)
  end
end

main()
