#!/bin/sh
set -e
set -u

if [ "$#" -ne 3 ] && [ "$#" -ne 4 ]; then
  exit 2
fi


command -v i3-msg > /dev/null

MAIN_DISP="$1"
DISP="$2"
POS="$3"

if [ "$4" = "y" ] ; then
  PRIMARY="--primary"
else
  PRIMARY=""
fi

if [ "$POS" != "right" ] && [ "$POS" != "left" ]; then
  exit 3
fi

I3CONFIG_FILE=${XDG_CONFIG_HOME:-$HOME/.config}/i3/config

xrandr
xrandr --output "$DISP" $PRIMARY
xrandr --output "$DISP" --auto --"$POS"-of "$MAIN_DISP" ; xrandr --output "$MAIN_DISP"

if [ -z "$PRIMARY" ]; then
  # shellcheck disable=2016
  sed -i --follow-symlinks 's/set $mon2 .*/set $mon2 '"$DISP"'/' "$I3CONFIG_FILE"
  # shellcheck disable=2016
  sed -i --follow-symlinks 's/set $mon1 .*/set $mon1 '"$MAIN_DISP"'/' "$I3CONFIG_FILE"
else
  # shellcheck disable=2016
  sed -i --follow-symlinks 's/set $mon2 .*/set $mon2 '"$MAIN_DISP"'/' "$I3CONFIG_FILE"
  # shellcheck disable=2016
  sed -i --follow-symlinks 's/set $mon1 .*/set $mon1 '"$DISP"'/' "$I3CONFIG_FILE"
fi


# check success
if [ "$(xrandr  | grep connected | grep -c -v disconnected)" = "2" ]; then
  printf 'GT_PROFILE="Dual"' > "$HOME"/.zsh/12_gnome_terminal_profile.zsh
fi


i3-msg restart
