#!/bin/sh
set -e
set -u

# Store the secret using the following:
# secret-tool store --label=2fa name NAME type 2fa

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 2FA_NAME"
  exit 1
fi
name="$1"


secret="$(secret-tool lookup type 2fa name $name)"

code="$(oathtool -b --totp "$secret")"

echo "Putting it in clipboard"
echo "$code"

# exits if failure with xclip (called outside of X)
echo "$code" | timeout 1 xclip || true

# timeout to deal with xclip hanging in some cases
timeout 1 xclip -selection primary -out | timeout 1 xclip -selection clipboard

