#!/bin/sh
set -e
set -u


if [ "${I3L_COLOR:-x}" = "x" ]; then
  color="$(python3 - <<EOF
import random
import socket

random.seed(socket.gethostname())
hexa = '0123456789abcdef'
print(''.join(random.choice(hexa) for _ in range(6)))
EOF
)"
else
  color="$I3L_COLOR"
fi


i3lock -c "$color"
(
xinput --set-prop 14 'Device Enabled' 0
xset dpms force off
while pgrep i3lock ; do
  sleep 1
done
xinput --set-prop 14 'Device Enabled' 1
) &
