#!/bin/sh
set -e
set -u
color="$(python3 - <<EOF
import random
import socket

random.seed(socket.gethostname())
hexa = '0123456789abcdef'
print(''.join(random.choice(hexa) for _ in range(6)))
EOF
)"


i3lock -c "$color"
