#!/usr/bin/env python3
import subprocess
import json

"""
Ideas:
    * swap on both displays (1 matches 11, etc.)
"""


def current_workspace(d):
    for s in d:
        if s['focused']:
            return s['name']


def switch_workspaces(ws1, ws2):
    subprocess.run(
        ['i3-msg',  f"rename workspace {ws2} to temporary; rename workspace {ws1} to {ws2}; rename workspace temporary to {ws1}"])


def swap_workspace_with_main(ws):
    if ws < 10:
        target = 1
    else:
        target = 11

    switch_workspaces(ws, target)


def swap_both_workspaces_with_mains(ws):
    swap_workspace_with_main(ws)
    swap_workspace_with_main(ws + 10 % 20)


def swap():
    out = subprocess.check_output(['i3-msg', '-t', 'get_workspaces'],
                                  encoding='utf-8')

    d = json.loads(out)

    current = current_workspace(d)

    if current is None or current == '1' or current == '10':
        print("failed")
        return

    current = int(current)

    swap_workspace_with_main(current)

    subprocess.run(["i3-msg", f"workspace {current}"])


if __name__ == '__main__':
    swap()
