#!/bin/sh
set -e
set -u
if [ "$#" != "1" ]; then
  echo "Usage: $0 DIRECTORY"
  exit 1
fi
DIRECTORY="$1"

LINK_CMD="ln -i -s"
safe_link(){
  if [ -L "$2" ]; then
    curr="$(readlink -n "$2")"
    if [ "$curr" = "$1" ]; then
      # do nothing
      true
    else
      echo "Changing symbolic link from:"
      echo "$curr"
      echo "To:"
      echo "$1"
      $LINK_CMD "$1" "$2"
    fi
  else
    printf "Creating link: %s\n" "$2"
    $LINK_CMD "$1" "$2"
  fi
  unset curr
}

cd "$(dirname "$0")"

# if [ ! "$0" = "./$(basename "$0")" ]; then
#   echo "Execute from base directory"
#   exit 1
# fi
echo "Install in $DIRECTORY:"
echo "Continue? [Y]"
read -r _
mkdir -p "$DIRECTORY"

for f in **/*; do
  echo "$f"
  if [ ! "$f" = "$(basename "$0")" ] && [ -x "$f" ] ; then
    safe_link "$(realpath $f)" "$DIRECTORY/$(basename $f)"
  else
    printf "Not installing %s\n" "$f"
  fi
done

for f in "$DIRECTORY"/* ; do
  if [ -h "$f" ] && [ ! -f "$(readlink -f "$f")" ]; then
    trash "$f"
  fi
done
