#!/bin/sh
set -u

timelapse=10
main(){
  echo "kill_bt_start"
  while sleep $timelapse; do
  if ! pgrep openvpn > /dev/null; then
    "$HOME"/code/scripts/kill_bt
  fi
  done
  echo "kill_bt_end"
}

main
