#!/bin/sh
set -u

safe_k(){
  if [ ! -z "$1" ]; then
    echo "trying to kill"
    kill "$1"
    sleep 1
    kill -9 "$1"
  fi
}


kill_bt(){
  # pkill "$(which deluge)"
  # safe_k "$(pidof "$(which qbittorrent)")" &
  safe_k "$(pidof "$(which transmission-gtk)")" &
  # pkill -9 /usr/bin/deluge
  wait
}

kill_bt > /dev/null 2>&1

timelapse=10
main(){
  echo "kill_bt_start"
  while sleep $timelapse; do
  if ! pgrep openvpn > /dev/null; then
    kill_bt
  fi
  done
  echo "kill_bt_end"
}

main
