#!/bin/sh
set -e
set -u

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 FILE"
  exit 1
fi

suffix="${1##*\.}"


f=$(mktemp --suff ."$suffix") && cp "$1" "$f"

(
  xdg-open "$f"
  rm "$f"
) &

echo Opening...
