#!/bin/sh
# Add a random album from $MPD_RANDOM_SOURCE_DIRECTORY to the mpd queue.
set -e
set -u

mpd_first_duplicate(){
  mpc -f "%position% \t %file%" playlist | awk ' {
  pos=$1
  $1=""
  map[$0]=map[$0]+1 ;
  if (map[$0] > 1) {
    print pos ;
    exit
  }
}'
}

mpd_delete_duplicates(){
  while true; do
    item="$(mpd_first_duplicate)"
    if [ -z "$item" ]; then
      break
    fi
    mpc del "$item"
  done
}

d="$(random_directory "$MPD_RANDOM_SOURCE_DIRECTORY")"
i="$(realpath --relative-to="$MPD_RANDOM_BASE_DIRECTORY" "$d")"



mpc add "$i"
mpd_delete_duplicates
mpc play
