#!/usr/bin/expect
spawn encrypt_mount $env(MUSIC_UUID)
expect {
  "Passphrase:" {
    set pass $env(MUSIC_PASS)\n
    send $pass
  }
}
interact


# to unmount:
# device="$(lsblk -r -f | grep $env(MUSIC_UUID) | cut -f1 -d' ')"
# udisksctl unmount -b /dev/dm-4
# sleep 2
# udisksctl lock -b /dev/$device
