#!/bin/sh
# http://wcm1.web.rice.edu/mutt-tips.html
set -e
set -u

MESSAGE="$(cat)"

# NEWALIAS=$(echo "${MESSAGE}" | grep ^"From: " | sed s/[\,\"\']//g | awk '{$1=""; if (NF == 3) {print "alias" $0;} else if (NF == 2) {print "alias" $0 $0;} else if (NF > 3) {print "alias", tolower($(NF-1))"-"tolower($2) $0;}}')

if addr=$(echo "$MESSAGE" | grep '^From: ' | sed "s/[\,\"\']//g" | grep -o '<.*>') ; then
  cleanaddr=$(echo "$addr" | sed 's/[<>]*//g')
  NEWALIAS="alias $cleanaddr $addr"

  if ! grep -Fxq "$NEWALIAS" "$HOME"/.mutt/aliases.txt ; then
    echo "$NEWALIAS" >> "$HOME"/.mutt/aliases.txt
  fi
fi

echo "$MESSAGE"
