#!/bin/sh
set -e
set -u
LOCK_FILE="$MOBILE_DIR"/config/mutt/aliases_lock

ignore(){
  printf "%s" "$*" | grep 'noreply\|no-reply\|announce\|list\|docs.google.com' > /dev/null
}

MESSAGE="$(cat)"

# grep -m 1 to stop after first match
if addr=$(printf "%s" "$MESSAGE" | grep -m 1 '^From: ' | sed "s/[\,\"\']//g" | grep -o '<.*>') ; then
  if ignore "$addr"; then
    printf "%s" "$MESSAGE"
    exit 0;
  fi

  cleanaddr=$(printf "%s" "$addr" | sed 's/[<>]*//g')
  NEWALIAS="alias $cleanaddr $addr"

  if ! grep -Fxq "$NEWALIAS" "$MOBILE_DIR"/config/mutt/aliases.txt ; then
    if [ ! -e "$LOCK_FILE" ]; then
      touch "$LOCK_FILE"
      printf "%s" "$NEWALIAS" >> "$MOBILE_DIR"/config/mutt/aliases.txt
      rm "$LOCK_FILE"
    fi
  fi
fi

printf "%s" "$MESSAGE"
