#!/bin/sh
set -e
set -u
path="/usr/bin/mutt"


command="${path##*/}"
folder="$HOME"/Documents/habits/"$command"_count
file="$folder"/"$(date --iso-8601)"

mkdir -p "$folder"
printf "%s\n" "$(date --iso-8601=minutes)" >> "$file"

# we could directly iterate over the line with awk and do "sleep 1" for every
# line, but we prefer to close the file ASAP instead.
wc -l "$file" | awk '{print "Waiting " $1 " seconds..." ; system("sleep " $1)}' && "$path" "$@"
