#!/bin/sh
set -e
set -u
# shellcheck source=/dev/null
. "$ZDOTDIR"/10_globals.zsh
# shellcheck source=/dev/null
. "$ZDOTDIR"/11_locals.zsh
OPENVPN_PID_FILE="/var/run/openvpn/openvpn.pid"

safe_k(){
  if [ -n "$1" ]; then
    echo "trying to kill"
    kill "$1"
    sleep 1
    kill -9 "$1"
  fi
}


kill_bt(){
  # pkill "$(which deluge)"
  safe_k "$(pidof "$(which qbittorrent)")" &
  safe_k "$(pidof "$(which transmission-gtk)")" &
  # pkill -9 /usr/bin/deluge
  wait
}

finish(){
  echo finishing
  kill_bt
}

trap finish 1 2 3 15

if pgrep openvpn; then
  echo "VPN already running?"
else
  cd "$VPN_CONFIG_DIR" && sudo openvpn --writepid "$OPENVPN_PID_FILE" --config cstorm_linux-balancer_udp.ovpn
  finish
fi
