#!/bin/sh
set -e
set -u
cd "$HOME"/mobile/0_planning || exit 2

# create panes
tmux split-window -h
tmux split-window
tmux select-pane -L
tmux split-window
tmux resize-pane -D 10
tmux select-pane -U

tmux respawn-pane -t top-right -k watch_plan

if [ "$(hostname)" = "hiq-work-deb" ]; then
  tmux respawn-pane -t bottom-right -k 'todo_watch t @work -@out'
else
  tmux respawn-pane -t bottom-right -k 'todo_watch t -@work -@out'
fi
vi activities.txt
tmux kill-pane
