#!/bin/sh
set -e
set -u
cd "$MOBILE_DIR"/0_planning || exit 2

# create panes
tmux split-window -h # -p 66
tmux split-window -h # -p 61
tmux select-layout even-horizontal


tmux select-pane -L
tmux select-pane -L

tmux resize-pane -t 1 -x 56

tmux respawn-pane -t 1 -k  'while true; do RUST_BACKTRACE=1 tiro -n -w -p history -s history ; echo "bug, exited..." ; sleep 2; done'

# tmux respawn-pane -t bottom-right -k "todo_watch t Y ${PLANTODO_FLAG:-}"
tmux respawn-pane -t 2 -k "todo_watch t Z ${PLANTODO_FLAG:-}"


# could remove parts of these -c and put e.g. in vimrc
# XXX: try small tw
vi -n -c 'set filetype=tiro' -c 'set tw=50' -c 'set commentstring=#\ %s' -c ':n' -c ':bp' activities.txt $MOBILE_DIR_WORK/0_planning/activities.txt
tmux kill-window
