#!/bin/sh
# Opens a temporary file containing primary selection prepended with '> ' with
# vi, and copies the result into the clipboard.
set -e
set -u
dir="${USERTMP:-/tmp}"/quote_vi
mkdir -p "$dir"
file="$dir"/"$(date -Ins)"
if [ "$1" = "y" ]; then
  printf "%s\n" "$(xclip -r -selection primary -out)" | while read -r line ; do printf "> %s\n" "$line" >> "$file" ; done
  printf "\n\n" >> "$file"
fi


vi +$ -c "set updatetime=1 | autocmd CursorHold,CursorHoldI * update" "$file"

# Need nohup to survive the exit of the script
cat "$file" | nohup xclip -i -selection clipboard > /dev/null

