#!/bin/sh
set -e
set -u
if ! command -v recordmydesktop ; then
  notify-send "recordmydesktop program missing!"
  exit 1
fi
if pgrep recordmydesktop ; then
  killall recordmydesktop
  notify-send "Stopped recording."
else
  notify-send "Starting recording."
  mkdir -p ~/.tmp/screencasts
  recordmydesktop --on-the-fly-encoding -o  ~/.tmp/screencasts/out.ogv
fi
