#!/bin/bash
{
  set -e
  set -u

  LIMIT="10"

# for MOBILE_DIR
. "${ZDOTDIR:-$HOME/.config/zsh}"/11_locals.zsh
tgt_opus="$MOBILE_MUSIC/opus"
tgt_flac="$MOBILE_MUSIC/flac"

# delete the folders in opus that are no longer in flac
find "$tgt_opus" -mindepth 1 -maxdepth 1 -type d -print0 | while IFS= read -d '' -r folder; do
if [ ! -d "$tgt_flac"/"$(basename "$folder")" ]; then
  trash "$folder"
fi
done


for ((i=1; i<=LIMIT; i++ )); do
  set +e
  p="$("$HOME"/.local/bin/rmusic.py)"
  if [ "$?" -eq 1 ]; then
    # no folder
    exit 0
  fi
  set -e
  folder_number="$(find "$tgt_flac" -mindepth 1 -maxdepth 1 -type d -printf 'A'| wc -c)"

  if [ "$folder_number" -ge "$LIMIT" ]; then
    exit 0
  fi


  mkdir -p "$tgt_opus"
  cp -r -n "$p" "$tgt_opus"

  printf "%s" "$p" >> "$tgt_opus"/"$(basename "$p")"/rmusic_path

  mv -n "$p" "$tgt_flac"

done
}
