#!/usr/bin/env sh
if [ -f "$ZDOTDIR"/11_locals.zsh ]; then
  . "$ZDOTDIR"/11_locals.zsh
  find "$IN_DIR"/msgs -type f -size +0 -exec notify-send "check msgs" \;
fi

if ! ps aux|grep '[s]ignal-desktop' ; then
  timeout 60 signal-desktop --start-in-tray &
fi

if ! ps aux|grep '[s]ignal-desktop-beta' ; then
  signal-desktop-beta "$@" &
fi
