#!/usr/bin/env sh
if [ -f "$ZDOTDIR"/11_locals.zsh ]; then
  . "$ZDOTDIR"/11_locals.zsh
  find "$MOBILE_DIR"/msgs -type f -size +0 -exec notify-send "check msgs" \;
  if [ -d "$MOBILE_DIR_WORK"/msgs ]; then
    find "$MOBILE_DIR_WORK"/msgs -type f -size +0 -exec notify-send "check msgs (work)" \;
  fi
fi

if ! ps aux|grep '[s]ignal-desktop' ; then
  timeout 60 signal-desktop --start-in-tray &
fi

if ! ps aux|grep '[s]ignal-desktop-beta' ; then
  signal-desktop-beta "$@" &
fi
