#!/bin/sh
# Switch mouse and keyboard to other host using solaar.

# Tolerating errors.
set +e
set -u
RETRIES=3

solaar config "$SOLAAR_KEYBOARD" change-host "$OTHER_SOLAAR_HOST"
solaar config "$SOLAAR_MOUSE" change-host "$OTHER_SOLAAR_HOST"

for i in {1.."$RETRIES"}; do
  sleep 1
  echo "Retrying just in case..."
  solaar config "$SOLAAR_KEYBOARD" change-host "$OTHER_SOLAAR_HOST"
  solaar config "$SOLAAR_MOUSE" change-host "$OTHER_SOLAAR_HOST"
done

