#!/bin/sh
# shellcheck disable=SC1090
. "$HOME"/.zsh/15_path.zsh
if [ ! -f .solhint.json ]; then
  cp "$HOME"/.config/solhint/solhint.json .solhint.json
  SOLHINTJSONSET="true"
fi

"$NPM_GLOBAL_BIN"/solhint "$@"

if [ ! -z "$SOLHINTJSONSET" ]; then
  rm .solhint.json
fi
