#!/bin/sh
if [ ! -f .solhint.json ]; then
  cp "$HOME"/.config/solhint/solhint.json .solhint.json
  SOLHINTJSONSET="true"
fi

"$NPM_GLOBAL_BIN"/solhint "$@"

if [ ! -z "${SOLHINTJSONSET+x}" ]; then
  rm .solhint.json
fi
