#!/bin/sh
set -u
set -x
. "$ZDOTDIR"/10_globals.zsh
. "$ZDOTDIR"/15_path.zsh
LOGFILE="$USERTMP"/so.log
LOGFILE="$USERTMP"/so.log
SOLAARCMD="solaar"
while true; do
  show="$($SOLAARCMD show)"
  date >> "$LOGFILE"
  printf "%s" "$show" | grep K780 && $SOLAARCMD config k780 fn-swap false >> "$LOGFILE" 2>&1
  sleep 180
done
