#!/bin/bash
set -e
set -u

# 2023-11-25 XXX: try to remove this after rebooting, should be enough to have it in .profile?
export XDG_CONFIG_DIR="${XDG_CONFIG_DIR:=$HOME/.config}"
export ZDOTDIR="${XDG_CONFIG_DIR:-$HOME/.config}/zsh"

# For USERTMP
if [ -f "$ZDOTDIR"/10_globals.zsh ]; then
  . "$ZDOTDIR"/10_globals.zsh || true
fi
if [ -f "$ZDOTDIR"/17_zshrc_corp.zsh ]; then
  . "$ZDOTDIR"/17_zshrc_corp.zsh
fi

if [ "${TIME_LOG_FOLDER:+z}" = z ]; then
  FOLDER="$TIME_LOG_FOLDER"
else
  FOLDER="${USERTMP:-$HOME/.tmp}"/timelogs
fi

mkdir -p "$FOLDER"

fn="$FOLDER"/time_log_"$(hostname --long)"
touch "$fn"

append_to_log_atomically(){
  log="$(date -Iseconds) $(hostname --long)"
  tmp="$(mktemp)"
  cp "$fn" "$tmp"
  printf "%s\n" "$log" >> "$tmp"

  mv "$tmp" "$fn"
}

append_to_log_atomically
