#!/bin/sh
set -e
set -u

summarize(){
  PREFIX="$1"
  FOLDER="$2"
  for f in "$PREFIX"*; do
    if [ -f "$f" ]; then
      wc -l "$f"
    fi
  done | awk 'BEGIN {i=1}
  prev_lines > $1 {system("cp " prev_content " '"$FOLDER/$PREFIX"'_" i".txt"); i++}
  {prev_lines=$1 ; prev_content=$2}
  '
}

FOLDER="summary"
mkdir -p "$FOLDER"
summarize "activities" "$FOLDER"
summarize "plan" "$FOLDER"
