#!/bin/sh
set -e
set -u
echo "Using files:"
find . -maxdepth 2 -type f -iname 'plan*' | sort

# could use this to find the right line...
# find . -maxdepth 2 -type f -iname 'plan*' -print0 | xargs -0 -r grep -h 'spent on' | tr ':' ' ' | gawk '

# ...but just assume the last line is the one we look for
find . -maxdepth 2 -type f -iname 'plan*' -exec tail -n 1 '{}' \; | tr ':' ' ' | gawk '
{ time[$NF] += $1 * 60 + $2}

function q(a,b){
  return (a - (a%b)) / b
}

function comp_hours(m){
  return q(m, 60)
}

function comp_minutes(m){
  return m - q(m,60) * 60
}

END {
for(activity in time){
  hours = int(time[activity] / 60)
  minutes = time[activity] - hours * 60
  if(minutes < 10)
    zero = "0"
  else
    zero = ""
    print "Time spent on " activity ": " hours "h" zero minutes
    if(activity == "@work"){
      hours_left = ENVIRON["WORK_HOURS"] - comp_hours(time[activity])
      if(hours_left > 0)
        print "Time left on " activity ": " hours_left "h" comp_minutes(ENVIRON["WORK_HOURS"]*60 - time[activity])
      }
    }
  }
  '
