#!/bin/sh
set -e
set -u
# shellcheck source=/dev/null
. "$HOME"/.zsh/11_locals.zsh

OLD_TODO="$TODO_DIR/main/.todo.txt.old"
TODO="$TODO_DIR/main/todo.txt"
TODOCLEAN="$TODO_DIR/main/.todo.txt.cur"

sed 's/^ *([a-Z]) //' "$TODO" > "$TODOCLEAN"

if [ -f "$OLD_TODO" ]; then
  tmp="$(mktemp)"
  if grep -F -x -f "$TODOCLEAN" "$OLD_TODO" > "$tmp" ; then
    echo "The following items have been on the list for a long time:"
    grep -E -v '@work|@out' "$tmp"
  fi
fi

mv "$TODOCLEAN" "$OLD_TODO"
