#!/bin/sh
# shellcheck disable=SC1090
# TODO: replace with python or something else
# XXX: avoid exiting for bogus reasons?
# set -e
# set -x
set -u

if [ "$#" -eq 0 ]; then
  echo "Usage: $0 TODO_TXT_COMMAND MIN_PRIORITY [SEARCH_TERMS]"
  exit 1
fi

. "$ZDOTDIR"/11_locals.zsh
tcmd="$1"
shift

if [ "${TODOWATCH_LASTPRIO:-nope}" = "nope" ]; then
  TODOWATCH_LASTPRIO="$1"
  shift
fi

twatch(){
  while true; do
    # probably useless, if fs is ok
    sync "$TODO_GLOBAL"/*
    # still got the bug with 0.4 under heavy load with only one sync
    sleep 0.4
    clear
    sync "$TODO_GLOBAL"/*

    if [ "${TODOWATCH_LEAVEWHENDONE:-}" = "y" ]; then
      # shellcheck disable=SC2068
      if ! ($tcmd -p lsp A-"$TODOWATCH_LASTPRIO" $@ | head -n -2 | grep -E -v '^[[:digit:]]{2} x ' ) > /dev/null ; then
        echo "No items anymore, exiting..."
        sleep 2
        # return 0
      fi
    fi

    # don't show done tasks

    # show tasks with no priorities
    t ls | grep -P '^[[:digit:]]{1,3} [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}'

    # shellcheck disable=SC2068
    $tcmd lsp A-"$TODOWATCH_LASTPRIO" $@ | grep -v '[[:digit:]][[:digit:]] x'
    # timeout to refresh periodically (useful when screen size changes), --foreground to kill via CTRL-C faster.
    timeout --foreground 120 inotifywait -qq -e create,modify "$TODO_GLOBAL"/* > /dev/null


  done
}

twatch "$@"
