#!/bin/sh
# shellcheck disable=SC1090
. "$HOME"/.zsh/11_locals.zsh
tcmd="$1"
shift


while true; do
  # still got the bug with 0.2 under heavy load...
  sleep 0.4
  # probably useless, if fs is ok
  sync "$TODO_GLOBAL"/*
  clear
  $tcmd ls "$@"
  inotifywait -qq -e create,modify "$TODO_DIR"/* > /dev/null
done
