#!/bin/sh
set -e
set -u

show_usage(){
  echo "Usage: $0 [opt] Contract_A.sol Contract_B.sol"
}

solc="solc --asm"

if [ "$#" -eq 3 ]; then
  solc="$solc"" --optimize --optimize-runs 20000"
  shift
fi

if [ "$#" -ne 2 ]; then
  show_usage
  exit 1
fi

f1="$(mktemp)"
printf "/* %s */\\n" "$1" > "$f1"

f2="$(mktemp)"
printf "/* %s */\\n" "$2" > "$f2"

$solc "$1" >> "$f1"
$solc "$2" >> "$f2"
vimdiff "$f1" "$f2"
