#!/bin/sh
set -e
set -u

show_usage(){
  echo "Usage: $0 Contract_A.sol Contract_B.sol"
}

if [ "$#" -ne 2 ]; then
  show_usage
  exit 1
fi

f1="$(mktemp)"
printf "/* %s */\n" "$1" > "$f1"

f2="$(mktemp)"
printf "/* %s */\n" "$2" > "$f2"

solc --optimize --asm "$1" >> "$f1"
solc --optimize --asm "$2" >> "$f2"
vimdiff "$f1" "$f2"
