#!/bin/sh
# set -e
set -u

# date -d "$date" compatible with short iso 8601 and long
watch_plan(){
  # refactor
  printf 'activities.txt' | entr -d sh -c '
  clear
  plan_fn=plan_"$(hostname)".txt
  CLICOLOR_FORCE=1 ./tiro < activities.txt | tee "$plan_fn"
  act_date="$(head -n 1 activities.txt)"
  subfolder=history/"$(date -d "$act_date" +"%Y-w%V")"/"$(date -d "$act_date" +"%Y-%m-%d")"
  mkdir -p "$subfolder"/archive
  cur_date="$(date --iso-8601=ns)"
  # ignore no match
  (cd $subfolder && mv plan_*.txt activities_*.txt archive/) 2>/dev/null
  cp "$plan_fn" "$subfolder"/plan_"$cur_date".txt
  cp activities.txt "$subfolder"/activities_"$cur_date".txt
  '
}


while true; do
  watch_plan
done
