#!/bin/sh
# set -e
set -u

watch_plan(){
    ./tiro < activities.txt > plan.txt
    clear
    cat plan.txt
    subfolder=history/"$(date +"%Y-%m-w%V")"/"$(date +"%Y-%m-%d")"
    mkdir -p "$subfolder"
    date="$(date --iso-8601=seconds)"
    cp plan.txt "$subfolder"/plan_"$date".txt
    cp activities.txt "$subfolder"/activities"$date".txt
    inotifywait -q -e create,modify . > /dev/null
}


while true; do
  watch_plan
done
